package swagger;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class  {
}


/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {
    Id int64 `json:"id"`
    FirstName string `json:"firstName"`
    LastName string `json:"lastName"`
    DateOfBirth string `json:"dateOfBirth"`
}
