---
swagger: "2.0"
info:
  description: "Title"
  version: "1.0.0"
  title: "Title"
host: "www"
basePath: "/rest"
schemes:
- "https"
paths:
  /test/v1/user:
    post:
      tags:
      - "MyUser"
      summary: "创建用户"
      operationId: "createUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user"
        description: "创建用户"
        required: true
        schema:
          $ref: "#/definitions/User"
        x-exportParamName: "User"
      responses:
        "200":
          description: "创建用户成功."
    put:
      tags:
      - "MyUser"
      summary: "修改用户"
      operationId: "modifyUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user"
        description: "修改用户"
        required: true
        schema:
          $ref: "#/definitions/User"
        x-exportParamName: "User"
      responses:
        "200":
          description: "修改用户成功."
  /test/v1/user/{id}:
    get:
      tags:
      - "MyUser"
      summary: "通过ID获取用户信息"
      operationId: "getUserById"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "通过ID获取用户信息"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "Id"
      responses:
        "200":
          description: "Retrieves family members by person id"
          schema:
            $ref: "#/definitions/User"
    delete:
      tags:
      - "MyUser"
      summary: "通过ID删除用户"
      operationId: "deleteUserById"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "通过ID删除用户"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "Id"
      responses:
        "200":
          description: "Delete family members by person id"
definitions:
  User:
    type: "object"
    required:
    - "dateOfBirth"
    - "firstName"
    - "id"
    - "lastName"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
        example: "John"
      lastName:
        type: "string"
        example: "Smith"
      dateOfBirth:
        type: "string"
        example: "1992-10-05"
    example:
      firstName: "John"
      lastName: "Smith"
      dateOfBirth: "1992-10-05"
      id: 0
